### PR TITLE
Python 3 compatibility.

### PR DESCRIPTION
**Pull request by szepeviktor**
Could you also enable [**Issues**](https://github.com/splitbrain/Watcher/settings)

### CODE REVIEW

**Comment by szepeviktor** [comment]
And still [`ValueError: can't have unbuffered text I/O`](http://stackoverflow.com/questions/107705/disable-output-buffering)

**Comment by szepeviktor** [comment]
@splitbrain  Could you finish it?

**Comment by szepeviktor** [comment]
@splitbrain Do you read these?

**Comment by splitbrain** [comment]
Applying this would break Python 2 compatibility, right? Since I'm running this on a system with python 2 only, I need the python 2 compatibility. If there's a way to be compatible with both, I'm open for suggestions.

**Comment by szepeviktor** [comment]
I think it won't break.

**Comment by szepeviktor** [comment]
https://github.com/getzze/Watcher/pull/2
@getzze Then could you please solve the remaining problem: [`ValueError: can't have unbuffered text I/O`](http://stackoverflow.com/questions/107705/disable-output-buffering)

**Comment by szepeviktor** [comment]
@getzze and merge PEP3143 related commits (maybe)

**Comment by getzze** [comment]
my fork is actually quite different from this version. And it's almost python3 compatible I would say

**Comment by DeepSpace2** [comment]
#18 See my pull request that is compatible with both Python 2.7.6 + and 3.4+ (at least as far as I tested :) ) @szepeviktor @splitbrain @getzze

**Pull request closed without merging**
